# Generated by Django 3.2.16 on 2024-11-16 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название встречи')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи')),
                ('requested_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи')),
                ('status', models.CharField(blank=True, choices=[('Запланировано', 'Запланировано'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено')], default='Неизвестно', max_length=20, null=True, verbose_name='Статус')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='Повестка встречи')),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный код')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Хост')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['date_time'],
            },
        ),
    ]
