# Generated by Django 3.2.16 on 2024-10-27 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Уникальный код'),
        ),
    ]
