# Generated by Django 3.2.16 on 2024-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Предпочтительная дата встречи'),
        ),
    ]
