# Generated by Django 3.2.16 on 2024-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_meeting_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='Дата встречи'),
        ),
    ]
