# Generated by Django 3.2.16 on 2024-10-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_meeting_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата встречи'),
        ),
    ]
