# Generated by Django 3.2.16 on 2024-10-29 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_alter_meeting_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название встречи'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(null=True, verbose_name='Повестка встречи'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
