# Generated by Django 3.2.16 on 2024-10-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20241029_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, null=True, verbose_name='Повестка встречи'),
        ),
    ]
