# Generated by Django 3.2.16 on 2024-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_meeting_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('Запланировано', 'Запланировано'), ('Завершено', 'Завершено'), ('Отменено', 'Отменено')], default='Неизвестно', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
